### ISSUE TITLE
Class On Boarding - Comment

### ISSUE THREAD

**Issue by goehrunr** [UW-POLS501/2018#4]
As someone who is entirely new to the language and structure of coding, I find this format a bit confusing and difficult to navigate. Are there any introductory resources you might suggest to help bring me up to speed? Even just some basic instructions about how to navigate GitHub might be helpful. Thanks. I look forward to class tomorrow.

**Comment by Yiyut** [comment]
Hi folks. As someone who is new to the language and only has the most basic statistics background, I feel pretty excited and a bit anxious taking this course, even if I want to learn it so very much. Let's work together!

**Comment by jrnold** [comment]
I'll add some resources (http://happygitwithr.com/rstudio-git-github.html is good), but we'll spend time bringing you up to speed. And you'll pick it up as we use it. I'll be introducing it in class. Right now I just wanted to make sure everyone gets an account because there's some logistics that we have to handle set organize the course.

**Comment by jrnold** [comment]
It seems like a lot ... and it is, but I'm operating with an assumption of essentially zero statistical or programming background. We'll work together to bring everyone up to speed to produce modern quant research!
